apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.reviews.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.reviews.port }}
  {{- if .Values.reviews.targetPort }}
    targetPort: {{ .Values.reviews.targetPort }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}